### PR TITLE
fix inconsistensies with cran guidelines

### LINKED ISSUE #123: Fix inconsistensies with CRAN guidelines
### Description
The package contains issues that need to be fixed in accordance with CRAN guidelines

- [ ] Use single quotes around package names, software names, and API names in *Title* and *Description* fields of `DESCRIPTION`.  
- [ ] Add a web reference (e.g. `<https://...>`) for the NASA Exoplanets API in `DESCRIPTION`.  
- [ ] Replace `\dontrun{}` with `\donttest{}` in examples.  
 - [ ] Only wrap functions that download data in `\donttest{}`.  
- [ ] Remove any code that **installs packages** inside functions, examples, or vignettes (see `R/app.R`).  

### References
- [CRAN cookbook: formatting software names](https://contributor.r-project.org/cran-cookbook/description_issues.html#formatting-software-names)  
- [CRAN cookbook: references in DESCRIPTION](https://contributor.r-project.org/cran-cookbook/description_issues.html#references)  
- [CRAN cookbook: structuring of examples](https://contributor.r-project.org/cran-cookbook/general_issues.html#structuring-of-examples)  
- [CRAN cookbook: installing software](https://contributor.r-project.org/cran-cookbook/code_issues.html#installing-software)

### PR DESCRIPTION
**Pull request by JKolomanski**
## Issue

Closes #123

## Description

Fixes several issues with CRAN guidelines:
- Use single quotes around package names, software names, and API names in *Title* and *Description* fields of `DESCRIPTION`.  
- Add a web reference for the NASA Exoplanets API in `DESCRIPTION`. 
- Replace `\dontrun{}` with `\donttest{}` in examples.
- Remove any code that dowloads external packages in `app.R`. Instead, show the user a message suggesting to install missing dependencies.

## How to test

Run `app()` with missing dependencies

## Contributor checklist

- [x] Code passes lintr checks
- [x] Code passes all unit tests
- [x] Package version is incremented

### CODE REVIEW

File: R/app.R [hunk 1]
```diff
@@ -58,45 +58,10 @@ check_app_dependencies = function() {
...
-      )
-    }
-
-    if (!requireNamespace("pak", silently = TRUE)) {
-      install.packages("pak")
-      requireNamespace("pak", quietly = TRUE)
-    }
-
-    pak::pak(missing_packages)
+      "Install missing packages to proceed"
```
Comment (m-kolomanski) [inline R/app.R]: nitpick:
```suggestion
      "Install missing packages to run the application."
```

**Review by m-kolomanski — APPROVED** [review]
LGTM
